name: JinChancyGale CI - master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: write-all

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current date
        id: get_date
        run: echo "DATE=$(TZ=Asia/Shanghai date +'%y%m%d')" >> $GITHUB_ENV

      - name: Get Git SHA
        id: get_sha
        run: echo "SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Set VERSION environment variable
        run: |
          ORIGINAL_VERSION=$(grep "mod_version=" gradle.properties | cut -d ' ' -f2 | sed 's/[^0-9.]//g')
          echo "Setting VERSION to ${ORIGINAL_VERSION}-${{ env.DATE }}-${{ env.SHA }}"
          echo "VERSION=${ORIGINAL_VERSION}-${{ env.DATE }}-${{ env.SHA }}" >> $GITHUB_ENV
          echo "VERSION_CHECK=${ORIGINAL_VERSION}-*-${{ env.SHA }}" >> $GITHUB_ENV

      - name: Check tags, commit messages and branches
        id: check_all
        run: |
          git fetch --tags
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          if [ -n "$(git tag -l "${{ env.VERSION_CHECK }}")" ]; then
            echo "Tag exists"
            echo "SKIP_BUILD=true" >> $GITHUB_ENV
          else
            echo "Tag does not exist"
            echo "SKIP_BUILD=false" >> $GITHUB_ENV
          fi
          if [[ "$COMMIT_MESSAGE" == "[skip]"* || ("$BRANCH_NAME" != "master" && "$COMMIT_MESSAGE" != "[ci]"*) ]]; then
            echo "PRE_RELEASE=true" >> $GITHUB_ENV
          else
            echo "PRE_RELEASE=false" >> $GITHUB_ENV
          fi

      - name: Update version in gradle.properties
        if: env.SKIP_BUILD == 'false'
        run: |
          sed -i "s/\(mod_version= \).*/\1'${{ env.VERSION }}'/" gradle.properties

      - name: Set up Zulu 17
        if: env.SKIP_BUILD == 'false'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Make gradlew executable
        if: env.SKIP_BUILD == 'false'
        run: chmod +x ./gradlew

      - name: Build with Gradle
        if: env.SKIP_BUILD == 'false'
        run: ./gradlew build

      - name: Rename JAR file
        if: env.SKIP_BUILD == 'false'
        id: rename_file
        run: |
          TARGET_JAR="Jinchancy-Gale-${{ env.VERSION }}"
          SOURCE_JAR=$(find build/libs -name "*.jar" -print -quit)
          echo "FINAL_JAR_NAME=${TARGET_JAR}" >> $GITHUB_ENV
          mv "${SOURCE_JAR}" "${TARGET_JAR}.jar"

      - name: Upload Artifact
        if: env.SKIP_BUILD == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FINAL_JAR_NAME }}
          path: ${{ env.FINAL_JAR_NAME }}.jar

      - name: Create Release and Upload JAR file
        if: env.SKIP_BUILD == 'false' && env.SKIP_RELEASE == 'false' && false # do not push now
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }} (Auto Build)"
          body: |
            ### Last commit
            #### Commit SHA:
            > ${{ github.sha }}
            #### Commit author:
            > ${{ github.event.head_commit.author.username }} 
            #### Commit time:
            > ${{ github.event.head_commit.timestamp }}
            #### Commit message:
            > ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
          makeLatest: true
          generateReleaseNotes: true
          artifacts: ${{ env.FINAL_JAR_NAME }}.jar
          token: ${{ secrets.GITHUB_TOKEN }}